// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ActionDocumentDataSlicesSlice =
  | PolygonTextSlice
  | ImageTextSlice
  | FootNoteSlice
  | IntroTextSlice
  | HeroSlice;

/**
 * Content for Action documents
 */
interface ActionDocumentData {
  /**
   * Slice Zone field in *Action*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: action.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ActionDocumentDataSlicesSlice> /**
   * Meta Description field in *Action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: action.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Action*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: action.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: action.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Action document from Prismic
 *
 * - **API ID**: `action`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ActionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ActionDocumentData>, "action", Lang>;

type ActionsDocumentDataSlicesSlice =
  | PolygonTextSlice
  | ImageTextSlice
  | DropDownContentSlice
  | HeroSlice;

/**
 * Content for Actions documents
 */
interface ActionsDocumentData {
  /**
   * Slice Zone field in *Actions*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: actions.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ActionsDocumentDataSlicesSlice> /**
   * Meta Description field in *Actions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: actions.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Actions*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: actions.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Actions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: actions.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Actions document from Prismic
 *
 * - **API ID**: `actions`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ActionsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ActionsDocumentData>,
    "actions",
    Lang
  >;

/**
 * Item in *Contact → contact*
 */
export interface ContactDocumentDataContactItem {
  /**
   * name field in *Contact → contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.contact[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * adress field in *Contact → contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.contact[].adress
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  adress: prismic.RichTextField;

  /**
   * phone field in *Contact → contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.contact[].phone
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phone: prismic.RichTextField;

  /**
   * mail field in *Contact → contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.contact[].mail
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  mail: prismic.RichTextField;

  /**
   * logo field in *Contact → contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.contact[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

type ContactDocumentDataSlicesSlice = never;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * intro field in *Contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.intro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  intro: prismic.RichTextField;

  /**
   * picture field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.picture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;

  /**
   * contact field in *Contact*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.contact[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contact: prismic.GroupField<Simplify<ContactDocumentDataContactItem>>;

  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

/**
 * Item in *Footer → footer_navigation*
 */
export interface FooterDocumentDataFooterNavigationItem {
  /**
   * label field in *Footer → footer_navigation*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * link field in *Footer → footer_navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Footer → social_media*
 */
export interface FooterDocumentDataSocialMediaItem {
  /**
   * label field in *Footer → social_media*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * link field in *Footer → social_media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Footer → contact*
 */
export interface FooterDocumentDataContactItem {
  /**
   * name field in *Footer → contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contact[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * adress field in *Footer → contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contact[].adress
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  adress: prismic.RichTextField;

  /**
   * phone field in *Footer → contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contact[].phone
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phone: prismic.RichTextField;

  /**
   * mail field in *Footer → contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contact[].mail
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  mail: prismic.RichTextField;
}

/**
 * Item in *Footer → legal_links*
 */
export interface FooterDocumentDataLegalLinksItem {
  /**
   * label field in *Footer → legal_links*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.legal_links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * link field in *Footer → legal_links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.legal_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * navigation_title field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.navigation_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  navigation_title: prismic.RichTextField;

  /**
   * footer_navigation field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_navigation: prismic.GroupField<
    Simplify<FooterDocumentDataFooterNavigationItem>
  >;

  /**
   * social_title field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  social_title: prismic.RichTextField;

  /**
   * social_media field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_media: prismic.GroupField<Simplify<FooterDocumentDataSocialMediaItem>>;

  /**
   * contact field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contact[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contact: prismic.GroupField<Simplify<FooterDocumentDataContactItem>>;

  /**
   * copyright field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copyright: prismic.RichTextField;

  /**
   * legal_links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.legal_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  legal_links: prismic.GroupField<Simplify<FooterDocumentDataLegalLinksItem>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;

/**
 * Item in *Header → navigation*
 */
export interface HeaderDocumentDataNavigationItem {
  /**
   * label field in *Header → navigation*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * link field in *Header → navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * navigation field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<HeaderDocumentDataNavigationItem>>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HeaderDocumentData>, "header", Lang>;

type HomeDocumentDataSlicesSlice =
  | ImageTextSlice
  | PolygonTextSlice
  | ActionResumeSlice
  | IntroTextSlice
  | CountryMapSlice
  | StatsDisplaySlice
  | FooterBannerSlice
  | HeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

type StoryDocumentDataSlicesSlice =
  | PolygonTextSlice
  | ImageTextSlice
  | IntroTextSlice
  | HeroSlice;

/**
 * Content for Story documents
 */
interface StoryDocumentData {
  /**
   * Slice Zone field in *Story*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: story.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<StoryDocumentDataSlicesSlice> /**
   * Meta Description field in *Story*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: story.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Story*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: story.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Story*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: story.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Story document from Prismic
 *
 * - **API ID**: `story`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<StoryDocumentData>, "story", Lang>;

export type AllDocumentTypes =
  | ActionDocument
  | ActionsDocument
  | ContactDocument
  | FooterDocument
  | HeaderDocument
  | HomeDocument
  | StoryDocument;

/**
 * Primary content in *ActionResume → Primary*
 */
export interface ActionResumeSliceDefaultPrimary {
  /**
   * title field in *ActionResume → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: action_resume.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *ActionResume → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: action_resume.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * link field in *ActionResume → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: action_resume.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *ActionResume → Items*
 */
export interface ActionResumeSliceDefaultItem {
  /**
   * name field in *ActionResume → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: action_resume.items[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * description field in *ActionResume → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: action_resume.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * link field in *ActionResume → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: action_resume.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * picture field in *ActionResume → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: action_resume.items[].picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;
}

/**
 * Default variation for ActionResume Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ActionResumeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ActionResumeSliceDefaultPrimary>,
  Simplify<ActionResumeSliceDefaultItem>
>;

/**
 * Slice variation for *ActionResume*
 */
type ActionResumeSliceVariation = ActionResumeSliceDefault;

/**
 * ActionResume Shared Slice
 *
 * - **API ID**: `action_resume`
 * - **Description**: ActionResume
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ActionResumeSlice = prismic.SharedSlice<
  "action_resume",
  ActionResumeSliceVariation
>;

/**
 * Primary content in *CountryMap → Primary*
 */
export interface CountryMapSliceDefaultPrimary {
  /**
   * title field in *CountryMap → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: country_map.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *CountryMap → Items*
 */
export interface CountryMapSliceDefaultItem {
  /**
   * name field in *CountryMap → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: country_map.items[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * description field in *CountryMap → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: country_map.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * picture_1 field in *CountryMap → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: country_map.items[].picture_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture_1: prismic.ImageField<never>;

  /**
   * picture_2 field in *CountryMap → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: country_map.items[].picture_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture_2: prismic.ImageField<never>;

  /**
   * picture_3 field in *CountryMap → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: country_map.items[].picture_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture_3: prismic.ImageField<never>;
}

/**
 * Default variation for CountryMap Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CountryMapSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CountryMapSliceDefaultPrimary>,
  Simplify<CountryMapSliceDefaultItem>
>;

/**
 * Slice variation for *CountryMap*
 */
type CountryMapSliceVariation = CountryMapSliceDefault;

/**
 * CountryMap Shared Slice
 *
 * - **API ID**: `country_map`
 * - **Description**: CountryMap
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CountryMapSlice = prismic.SharedSlice<
  "country_map",
  CountryMapSliceVariation
>;

/**
 * Primary content in *DropDownContent → Items*
 */
export interface DropDownContentSliceDefaultItem {
  /**
   * title field in *DropDownContent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: drop_down_content.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *DropDownContent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: drop_down_content.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for DropDownContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DropDownContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<DropDownContentSliceDefaultItem>
>;

/**
 * Slice variation for *DropDownContent*
 */
type DropDownContentSliceVariation = DropDownContentSliceDefault;

/**
 * DropDownContent Shared Slice
 *
 * - **API ID**: `drop_down_content`
 * - **Description**: DropDownContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DropDownContentSlice = prismic.SharedSlice<
  "drop_down_content",
  DropDownContentSliceVariation
>;

/**
 * Primary content in *FootNote → Primary*
 */
export interface FootNoteSliceDefaultPrimary {
  /**
   * text field in *FootNote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foot_note.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for FootNote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FootNoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FootNoteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FootNote*
 */
type FootNoteSliceVariation = FootNoteSliceDefault;

/**
 * FootNote Shared Slice
 *
 * - **API ID**: `foot_note`
 * - **Description**: FootNote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FootNoteSlice = prismic.SharedSlice<
  "foot_note",
  FootNoteSliceVariation
>;

/**
 * Primary content in *FooterBanner → Primary*
 */
export interface FooterBannerSliceDefaultPrimary {
  /**
   * title field in *FooterBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_banner.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *FooterBanner → Items*
 */
export interface FooterBannerSliceDefaultItem {
  /**
   * picture field in *FooterBanner → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_banner.items[].picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;
}

/**
 * Default variation for FooterBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterBannerSliceDefaultPrimary>,
  Simplify<FooterBannerSliceDefaultItem>
>;

/**
 * Slice variation for *FooterBanner*
 */
type FooterBannerSliceVariation = FooterBannerSliceDefault;

/**
 * FooterBanner Shared Slice
 *
 * - **API ID**: `footer_banner`
 * - **Description**: FooterBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterBannerSlice = prismic.SharedSlice<
  "footer_banner",
  FooterBannerSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * title field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceDefaultItem {
  /**
   * slide field in *Hero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].slide
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  slide: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  Simplify<HeroSliceDefaultItem>
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceHeroAboutPrimary {
  /**
   * text field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * video field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkField;
}

/**
 * Hero About variation for Hero Slice
 *
 * - **API ID**: `heroAbout`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceHeroAbout = prismic.SharedSliceVariation<
  "heroAbout",
  Simplify<HeroSliceHeroAboutPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceHeroTextPrimary {
  /**
   * text field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Hero Text variation for Hero Slice
 *
 * - **API ID**: `heroText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceHeroText = prismic.SharedSliceVariation<
  "heroText",
  Simplify<HeroSliceHeroTextPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceHeroTextImagePrimary {
  /**
   * text field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * picture field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;
}

/**
 * HeroTextImage variation for Hero Slice
 *
 * - **API ID**: `heroTextImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceHeroTextImage = prismic.SharedSliceVariation<
  "heroTextImage",
  Simplify<HeroSliceHeroTextImagePrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation =
  | HeroSliceDefault
  | HeroSliceHeroAbout
  | HeroSliceHeroText
  | HeroSliceHeroTextImage;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImageText → Primary*
 */
export interface ImageTextSliceDefaultPrimary {
  /**
   * title field in *ImageText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *ImageText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * link field in *ImageText → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * picture field in *ImageText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.primary.picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;

  /**
   * reversed field in *ImageText → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_text.primary.reversed
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  reversed: prismic.BooleanField;
}

/**
 * Default variation for ImageText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImageText → Primary*
 */
export interface ImageTextSliceWithTwoPicturesPrimary {
  /**
   * title field in *ImageText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *ImageText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * link field in *ImageText → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * primary_picture field in *ImageText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.primary.primary_picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  primary_picture: prismic.ImageField<never>;

  /**
   * secondary_picture field in *ImageText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.primary.secondary_picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  secondary_picture: prismic.ImageField<never>;
}

/**
 * WithTwoPictures variation for ImageText Slice
 *
 * - **API ID**: `withTwoPictures`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextSliceWithTwoPictures = prismic.SharedSliceVariation<
  "withTwoPictures",
  Simplify<ImageTextSliceWithTwoPicturesPrimary>,
  never
>;

/**
 * Slice variation for *ImageText*
 */
type ImageTextSliceVariation =
  | ImageTextSliceDefault
  | ImageTextSliceWithTwoPictures;

/**
 * ImageText Shared Slice
 *
 * - **API ID**: `image_text`
 * - **Description**: ImageText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextSlice = prismic.SharedSlice<
  "image_text",
  ImageTextSliceVariation
>;

/**
 * Primary content in *IntroText → Primary*
 */
export interface IntroTextSliceDefaultPrimary {
  /**
   * title field in *IntroText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *IntroText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for IntroText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntroTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *IntroText → Primary*
 */
export interface IntroTextSliceWithPolygonPrimary {
  /**
   * title field in *IntroText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *IntroText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * WithPolygon variation for IntroText Slice
 *
 * - **API ID**: `withPolygon`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroTextSliceWithPolygon = prismic.SharedSliceVariation<
  "withPolygon",
  Simplify<IntroTextSliceWithPolygonPrimary>,
  never
>;

/**
 * Slice variation for *IntroText*
 */
type IntroTextSliceVariation =
  | IntroTextSliceDefault
  | IntroTextSliceWithPolygon;

/**
 * IntroText Shared Slice
 *
 * - **API ID**: `intro_text`
 * - **Description**: IntroText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroTextSlice = prismic.SharedSlice<
  "intro_text",
  IntroTextSliceVariation
>;

/**
 * Primary content in *PolygonText → Primary*
 */
export interface PolygonTextSliceDefaultPrimary {
  /**
   * text field in *PolygonText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: polygon_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for PolygonText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PolygonTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PolygonTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *PolygonText → Primary*
 */
export interface PolygonTextSliceCenteredPrimary {
  /**
   * text field in *PolygonText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: polygon_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Centered variation for PolygonText Slice
 *
 * - **API ID**: `centered`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PolygonTextSliceCentered = prismic.SharedSliceVariation<
  "centered",
  Simplify<PolygonTextSliceCenteredPrimary>,
  never
>;

/**
 * Slice variation for *PolygonText*
 */
type PolygonTextSliceVariation =
  | PolygonTextSliceDefault
  | PolygonTextSliceCentered;

/**
 * PolygonText Shared Slice
 *
 * - **API ID**: `polygon_text`
 * - **Description**: PolygonText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PolygonTextSlice = prismic.SharedSlice<
  "polygon_text",
  PolygonTextSliceVariation
>;

/**
 * Primary content in *StatsDisplay → Primary*
 */
export interface StatsDisplaySliceDefaultPrimary {
  /**
   * title field in *StatsDisplay → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_display.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *StatsDisplay → Items*
 */
export interface StatsDisplaySliceDefaultItem {
  /**
   * text field in *StatsDisplay → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_display.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * stat field in *StatsDisplay → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_display.items[].stat
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  stat: prismic.RichTextField;

  /**
   * picture field in *StatsDisplay → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_display.items[].picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;
}

/**
 * Default variation for StatsDisplay Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatsDisplaySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StatsDisplaySliceDefaultPrimary>,
  Simplify<StatsDisplaySliceDefaultItem>
>;

/**
 * Slice variation for *StatsDisplay*
 */
type StatsDisplaySliceVariation = StatsDisplaySliceDefault;

/**
 * StatsDisplay Shared Slice
 *
 * - **API ID**: `stats_display`
 * - **Description**: StatsDisplay
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatsDisplaySlice = prismic.SharedSlice<
  "stats_display",
  StatsDisplaySliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ActionDocument,
      ActionDocumentData,
      ActionDocumentDataSlicesSlice,
      ActionsDocument,
      ActionsDocumentData,
      ActionsDocumentDataSlicesSlice,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataContactItem,
      ContactDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataFooterNavigationItem,
      FooterDocumentDataSocialMediaItem,
      FooterDocumentDataContactItem,
      FooterDocumentDataLegalLinksItem,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataNavigationItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      StoryDocument,
      StoryDocumentData,
      StoryDocumentDataSlicesSlice,
      AllDocumentTypes,
      ActionResumeSlice,
      ActionResumeSliceDefaultPrimary,
      ActionResumeSliceDefaultItem,
      ActionResumeSliceVariation,
      ActionResumeSliceDefault,
      CountryMapSlice,
      CountryMapSliceDefaultPrimary,
      CountryMapSliceDefaultItem,
      CountryMapSliceVariation,
      CountryMapSliceDefault,
      DropDownContentSlice,
      DropDownContentSliceDefaultItem,
      DropDownContentSliceVariation,
      DropDownContentSliceDefault,
      FootNoteSlice,
      FootNoteSliceDefaultPrimary,
      FootNoteSliceVariation,
      FootNoteSliceDefault,
      FooterBannerSlice,
      FooterBannerSliceDefaultPrimary,
      FooterBannerSliceDefaultItem,
      FooterBannerSliceVariation,
      FooterBannerSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefaultItem,
      HeroSliceHeroAboutPrimary,
      HeroSliceHeroTextPrimary,
      HeroSliceHeroTextImagePrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceHeroAbout,
      HeroSliceHeroText,
      HeroSliceHeroTextImage,
      ImageTextSlice,
      ImageTextSliceDefaultPrimary,
      ImageTextSliceWithTwoPicturesPrimary,
      ImageTextSliceVariation,
      ImageTextSliceDefault,
      ImageTextSliceWithTwoPictures,
      IntroTextSlice,
      IntroTextSliceDefaultPrimary,
      IntroTextSliceWithPolygonPrimary,
      IntroTextSliceVariation,
      IntroTextSliceDefault,
      IntroTextSliceWithPolygon,
      PolygonTextSlice,
      PolygonTextSliceDefaultPrimary,
      PolygonTextSliceCenteredPrimary,
      PolygonTextSliceVariation,
      PolygonTextSliceDefault,
      PolygonTextSliceCentered,
      StatsDisplaySlice,
      StatsDisplaySliceDefaultPrimary,
      StatsDisplaySliceDefaultItem,
      StatsDisplaySliceVariation,
      StatsDisplaySliceDefault,
    };
  }
}
