// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  action_resume: defineAsyncComponent(() => import("./ActionResume/index.vue")),
  country_map: defineAsyncComponent(() => import("./CountryMap/index.vue")),
  drop_down_content: defineAsyncComponent(
    () => import("./DropDownContent/index.vue"),
  ),
  foot_note: defineAsyncComponent(() => import("./FootNote/index.vue")),
  footer_banner: defineAsyncComponent(() => import("./FooterBanner/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  image_text: defineAsyncComponent(() => import("./ImageText/index.vue")),
  intro_text: defineAsyncComponent(() => import("./IntroText/index.vue")),
  polygon_text: defineAsyncComponent(() => import("./PolygonText/index.vue")),
  stats_display: defineAsyncComponent(() => import("./StatsDisplay/index.vue")),
});
